### PR TITLE
Fix typos not found by codespell

### LINKED ISSUE #327: 'average' not 'avarage'
https://github.com/GEANT/CAT/blob/b36976e2246a01dde08a359149f1316a38198ccd/translation/web_admin.pot#L3142

I couldn't fix this in Transifex, so... can you fix it here? :-)

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #327.

### CODE REVIEW

File: web/lib/admin/MapOpenLayers.php [hunk 1]
```diff
@@ -55,11 +55,11 @@ public function htmlHeadCode() {
         var addressService = 'https://nominatim.openstreetmap.org/search'; // the address search service
         var map; // the main map
         var markersArray = new Array(); // holds  all saved locations
-        var extent; // the boundng box for locations
+        var extent; // the bounding box for locations
         var selectedMarker; // used to pass information about market to be identified
         var jmarkers; // set in the surrounding PHP script as a json array to pass saved locations
         var markersSource = new ol.source.Vector(); // the vector source for locations
-        var tmpSource = new ol.source.Vector(); // the vector source for temporaty markers
+        var tmpSource = new ol.source.Vector(); // the vector source for temporary markers
```
Comment (DimitriPapadopoulos) [inline web/lib/admin/MapOpenLayers.php:62]: I hope I got this right.

File: web/lib/admin/MapOpenLayers.php [hunk 2]
```diff
@@ -70,7 +70,7 @@ public function htmlHeadCode() {
             src: '../resources/images/icons/location_marker_highlighted.png'
         });        
 
-        var circle =  new ol.style.Circle({ // the temporatu icon
+        var circle =  new ol.style.Circle({ // the temporary icon
```
Comment (DimitriPapadopoulos) [inline web/lib/admin/MapOpenLayers.php:73]: Same here, I hope I got this right.

File: web/lib/admin/MapNone.php [hunk 3]
```diff
@@ -48,10 +48,10 @@ public function htmlHeadCode() {
         // no magic required if you want to nothing at all.
         return "<script>
             function locateMe() {
-                navigator.geolocation.getCurrentPosition(locate_succes,locate_fail,{maximumAge:3600000, timeout:5000});
+                navigator.geolocation.getCurrentPosition(locate_success,locate_fail,{maximumAge:3600000, timeout:5000});
             }
 
-            function locate_succes(p) {
+            function locate_success(p) {
```
Comment (DimitriPapadopoulos) [inline web/lib/admin/MapNone.php:54]: Is this function part of an API that cannot be changed without breaking compatibility?

File: core/AbstractProfile.php [hunk 4]
```diff
@@ -254,7 +254,7 @@ public static function significantChanges($old, $new)
      * 
      * @return array of arrays of the form [['level' => $level, 'explanation' => $explanation, 'reason' => $reason]];
      */
-    public function openroamingRedinessTest() {
+    public function openroamingReadinessTest() {
```
Comment (DimitriPapadopoulos) [inline core/AbstractProfile.php:257]: Is this function part of an API that cannot be changed without breaking compatibility?

**Comment by twoln** [comment]
I am not completely sure that I am correct here but it seems that updating the .po files is pointless. The current translation workflow will pull the .pot files into Transifex where people will manage the translations. If we correct a misspelled word it will be reflected in a new source string so people will just need to do the translation again. While correcting .po files may be useful to correct a running service, doing so at this stage seems a waste of time. I could run the merge but then when we prepare for the distribution we will overwrite things with files from Transifex anyway.
